name: task-manager-check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          pip install uv
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Open Web Client Directory
        run: |
          ls -la
      - name: Run test coverage
        env:
          SECRET_KEY: 'django-ci-test-key-fake-123'
        run: |
          make test-coverage
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=MandosGrogu_python-project-52
            -Dsonar.organization=mandosgrogu-2
            -Dsonar.python.coverage.reportPaths=coverage.xml
